
name: one_batch_test_cpu_config

version: one_batch_test_cpu

trainer:
  val_check_interval: 0.1
  check_val_every_n_epoch: &log_every_n_steps 1
  log_every_n_steps: 5
  precision: 32
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  accelerator: cpu
  max_steps: 1000

model:
  log_every_n_steps: *log_every_n_steps

  encoder:
    target_cls: asr.submodules.encoder.BaseLineEncoder
    n_mels: 64
    fc_hidden: &fc_hidden 512

  decoder:
    target_cls: asr.submodules.decoder.BaseLineDecoder
    fc_hidden: *fc_hidden
    n_class: 28

  text_encoder:
    target_cls: asr.text_encoder.CTCCharTextEncoder
    alphabet: [
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
      'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ',
    ]

  train_dataloader:
    batch_size: 8
    num_workers: 1
    shuffle: True
    pin_memory: True
    drop_last: False

    dataset:
      target_cls: asr.data.ASRDataset
      manifest_path: /Users/grigoryfedorov/Desktop/asr_project_template/test_data/index.tsv
      max_audio_length: 20.0
      max_text_length: 200
      log_spec: True
    
      wave_aug: null
      spec_aug: null
  
      wave2spec: &wave2spec
        target_cls: torchaudio.transforms.MelSpectrogram
        n_mels: 64

  val_dataloader:
    batch_size: 8
    num_workers: 1
    shuffle: False
    pin_memory: True
    drop_last: False

    dataset:
      target_cls: asr.data.ASRDataset
      manifest_path: /Users/grigoryfedorov/Desktop/asr_project_template/test_data/index.tsv
      max_audio_length: 20.0
      max_text_length: 200
  
      wave2spec: *wave2spec

  loss:
    target_cls: torch.nn.CTCLoss

  optim:
    target_cls: torch.optim.Adam
    lr: 3e-4

  lr_scheduler:
    target_cls: torch.optim.lr_scheduler.OneCycleLR
    steps_per_epoch: 100
    epochs: 50
    anneal_strategy: cos
    max_lr: 3e-4
    pct_start: 0.2
